---
- name: install artifactory
  hosts: ci
  become: yes
  tasks:
  - name: artifactory add repo
    get_url:
      url: https://releases.jfrog.io/artifactory/artifactory-rpms/artifactory-rpms.repo
      dest: /etc/yum.repos.d/jfrog-artifactory-rpms.repo
  - name: install artifactory
    yum:
      update_cache: yes
      name: jfrog-artifactory-oss
      state: present
  - name: start artifactory service
    systemd:
      name: artifactory
      state: started
